name: veggytably_customer
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  dio: ^5.0.2
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_markdown: ^0.6.9
  flutter_secure_storage: ^8.0.0
  geolocator: ^9.0.2
  get: ^4.6.5
  image_picker: ^0.8.6+4
  intl: ^0.18.0
  latlong2: ^0.8.0
  shared_preferences: ^2.0.18
  socket_io_client: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
